[alookso_gwanyul]
title = "alookso ─ 천관율"
url = "https://alook.so/users/8letPq"
entrySelector = "//section[1]/section/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"

[alookso_somewon]
title = "alookso ─ 윤성원"
url = "https://alook.so/users/8Ogtna"
entrySelector = "//section[1]/section/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"

[alookso_showdam]
title = "alookso ─ 조소담"
url = "https://alook.so/users/qQPtde"
entrySelector = "//section[1]/section/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
