[figk]
title = "FIGK"
url = "https://figk.net/text"
entrySelector = "div.styles_TextFIGKContainer__1iZw8"
titleSelector = "div.styles_Title__2bpAt"
linkSelector = "div.styles_ToolBox__2vzTh > a"
authorSelector = "h3"
contentSelector = "div.styles_Content__34J2v"
waitUntil = "networkidle"
onFail = "stale"

[figk_origin]
title = "FIGK"
url = "https://figk.net/text"
entrySelector = "div.styles_TextFIGKContainer__1iZw8"
titleSelector = "h2.styles_Subtitle__2PhmW"
linkSelector = "div.styles_ToolBox__2vzTh > a"
contentSelector = "h3"
waitUntil = "networkidle"
onFail = "stale"

[alookso_alookso]
title = "alookso ─ alookso"
url = "https://alook.so/users/x4WtnB"
entrySelector = "//html/body/main/div/div[2]/div/div/section[1]/section/div/div"
titleSelector = "//div[2]/h5"
linkSelector = "//div[2]/h5/a"
contentSelector = "//div[2]/h6/a/div[@class='trix-content']"
dateSelector = "//div[1]/div/div/div[2]/div[@class='font-light text-gray-400 text-xxs']"
dateFormat = "yyyy.MM.dd."
waitUntil = "networkidle"
onFail = "stale"

[alookso_gwanyul]
title = "alookso ─ 천관율"
url = "https://alook.so/users/8letPq"
entrySelector = "//html/body/main/div/div[2]/div/div/section[1]/section/div/div/div[@class='flex-auto mt-2 space-y-2']/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_somewon]
title = "alookso ─ 윤성원"
url = "https://alook.so/users/8Ogtna"
entrySelector = "//html/body/main/div/div[2]/div/div/section[1]/section/div/div/div[@class='flex-auto mt-2 space-y-2']/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_showdam]
title = "alookso ─ 조소담"
url = "https://alook.so/users/qQPtde"
entrySelector = "//html/body/main/div/div[2]/div/div/section[1]/section/div/div/div[@class='flex-auto mt-2 space-y-2']/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_sooyoung]
title = "alookso ─ 윤수영"
url = "https://alook.so/users/xwVtDZ"
entrySelector = "//html/body/main/div/div[2]/div/div/section[1]/section/div/div/div[@class='flex-auto mt-2 space-y-2']/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_soventure]
title = "alookso ─ 이재웅"
url = "https://alook.so/users/6mt7oo"
entrySelector = "//html/body/main/div/div[2]/div/div/section[1]/section/div/div/div[@class='flex-auto mt-2 space-y-2']/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_yozoh]
title = "alookso ─ 신요조"
url = "https://alook.so/users/8Ogtd9"
entrySelector = "//html/body/main/div/div[2]/div/div/section[1]/section/div/div/div[@class='flex-auto mt-2 space-y-2']/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_janghyeyeong]
title = "alookso ─ 장혜영"
url = "https://alook.so/users/8XGtO0"
entrySelector = "//html/body/main/div/div[2]/div/div/section[1]/section/div/div/div[@class='flex-auto mt-2 space-y-2']/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_datacow]
title = "alookso ─ 데이터카우"
url = "https://alook.so/users/bA6tp1"
entrySelector = "//html/body/main/div/div[2]/div/div/section[1]/section/div/div/div[@class='flex-auto mt-2 space-y-2']/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"
