[figk]
title = "FIGK"
url = "https://figk.net/text"
entrySelector = "div.styles_TextFIGKContainer__1iZw8"
titleSelector = "div.styles_Title__2bpAt"
linkSelector = "div.styles_ToolBox__2vzTh > a"
authorSelector = "h3"
contentSelector = "div.styles_Content__34J2v"
waitUntil = "networkidle"
onFail = "stale"

[figk_origin]
title = "FIGK"
url = "https://figk.net/text"
entrySelector = "div.styles_TextFIGKContainer__1iZw8"
titleSelector = "h2.styles_Subtitle__2PhmW"
linkSelector = "div.styles_ToolBox__2vzTh > a"
contentSelector = "h3"
waitUntil = "networkidle"
onFail = "stale"

[alookso_alookso]
title = "alookso ─ alookso"
url = "https://alook.so/users/x4WtnB"
entrySelector = "//section[1]/div/div/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_gwanyul]
title = "alookso ─ 천관율"
url = "https://alook.so/users/8letPq"
entrySelector = "section div div div[class='px-4 py-4 lg:px-0 md:py-6'] div[id^='post_'] div[class='flex-auto mt-2 space-y-2']  h5[data-qa='post-title']"
titleSelector = "a[class='text-xl text-gray-800 font-semibold line-clamp-2']"
linkSelector = "a[class='text-xl text-gray-800 font-semibold line-clamp-2']"
waitUntil = "networkidle"
onFail = "stale"

[alookso_somewon]
title = "alookso ─ 윤성원"
url = "https://alook.so/users/8Ogtna"
entrySelector = "//section[1]/div/div/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_showdam]
title = "alookso ─ 조소담"
url = "https://alook.so/users/qQPtde"
entrySelector = "//section[1]/div/div/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_sooyoung]
title = "alookso ─ 윤수영"
url = "https://alook.so/users/xwVtDZ"
entrySelector = "//section[1]/div/div/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_soventure]
title = "alookso ─ 이재웅"
url = "https://alook.so/users/6mt7oo"
entrySelector = "//section[1]/div/div/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_yozoh]
title = "alookso ─ 신요조"
url = "https://alook.so/users/8Ogtd9"
entrySelector = "//section[1]/div/div/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_janghyeyeong]
title = "alookso ─ 장혜영"
url = "https://alook.so/users/8XGtO0"
entrySelector = "//section[1]/div/div/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"

[alookso_datacow]
title = "alookso ─ 데이터카우"
url = "https://alook.so/users/bA6tp1"
entrySelector = "//section[1]/div/div/div/div/div/h5"
titleSelector = "//a"
linkSelector = "//a"
waitUntil = "networkidle"
onFail = "stale"
